### ISSUE TITLE
Ability to run simpla on own server

### ISSUE THREAD

**Issue by fracz** [simplaio/simpla#11]
I'm sure there are some projects that would greatly benefit from your idea, but they won't because of security issues or the fact that they work in LAN environment. Sometimes we just can't allow storing the data _somewhere in the world_.

I don't know how this relates to your idea but in my opinion there should be an option to install a _simpla server_ locally and use it instead of public service. Just like the https://prerender.io/ - you can use it _as is_ or install the prerender server locally.

**Comment by seaneking** [comment]
Yep we would love to do this in future. The core of Simpla's API is pretty basic, it just sets/gets JSON key:value pairs. Obviously there's a lot more to it in our platform, but for a simple single-site host that + auth is all you would need. Then it would just be a matter of pointing Simpla to your own API instead of ours (soon to be configurable in [simplaio/simpla](https://github.com/simplaio/simpla)). 

We don't have the resources to build something like this at the moment, but once our API is documented we'd welcome other open-souce projects that let you self-host Simpla.

**Comment by fracz** [comment]
I supposed it's simple but I could not verify it as `simpla-core` repo is not public :-)

Having a standard API would allow to write own backends - exactly. But if I use third-party backend (or one I've written myself) for auth & data store, then your great idea is downgraded to a few simple `<simpla-*` web components, isn't it? I mean, how would it differ from for example [angular-contenteditable](https://github.com/akatov/angular-contenteditable) (besides it's angular-specific)?

**Comment by seaneking** [comment]
`simpla-core` is public now (though not documented) :-)

So the idea behind Simpla is to provide a common base to build a whole ecosystem of content management tools on top of. In the future we'll make it super easy to quickly put together your own Simpla elements, use other elements from the community, etc. 

So while angular-contenteditable is kind of like a low-level version of `simpla-text`, you also have `simpla-img` for image editing, `simpla-block` for data structuring, upcoming tools like repeaters, etc. and they all work together seamlessly and talk to the same API.

**Comment by seaneking** [comment]
Just a quick update on this - the API that Simpla points to is now configurable when you initialise the Js SDK, like so:

```js
Simpla({
  api: 'https://api.vaadin.com'
});
```

You can also differentiate between auth and data endpoints for multi-tenancy setups (this is how Simpla's current API works) 

```js
Simpla({
  api: {
    auth: '...',
    data: '...'
  }
});
```

Again, this isn't documented yet because we haven't got around to opening up our RESTful interface, so it's of pretty limited use right now.

**Comment by seaneking** [comment]
Simpla is now completely open source, and while it relies on GitHub as a 'backend', all you content is open and yours. We'd also like to introduce different storage adapters (eg: custom node, filesystem, etc) in future, but that's the topic for another issue.
