### ISSUE TITLE
Can I use simpla with this Elm like library?

### ISSUE THREAD

**Issue by datnamer** [simplaio/simpla#27]
Hello,

[Escher](http://escher-jl.org/) is an elm like library for Julia  that allows the creation of composable reactive web apps without using HTML/CSS, though it can express the full breadth of the latter. 

It can wrap arbitrary web elements... would it be possible to use simpla with this?

**Comment by seaneking** [comment]
I should imagine so, as long as you can spit out Simpla's HTML to the DOM somewhere then it should work. 

/cc @bedeoverend

**Comment by bedeoverend** [comment]
Shouldn't be a problem - I haven't played with Escher myself, but from a quick look at the docs, it looks like it uses WebComponents + Polymer itself, so it should work really well with Simpla.

The only thing to be aware of, you should install (Simpla locally)[https://www.simpla.io/docs#hosting-elements-locally], rather than hotlinking from our CDN so as to avoid dependency conflicts.

Let us know how you go with it!

**Comment by datnamer** [comment]
Thanks!!

**Comment by seaneking** [comment]
Will close this, let us know if any problems arise!
