### ISSUE TITLE
Website is down...

### ISSUE THREAD

**Issue by iamchriswick** [simplaio/simpla#58]

**Comment by seaneking** [comment]
Thanks for reporting! We're investigating the root cause, looks like it might be something upstream with our static site host. 

Will update here and on status.simpla.io

Sorry! Will get back up and running ASAP. And I have confirmed that this outage is just for the Simpla.io website, projects and the API are unaffected

**Comment by seaneking** [comment]
This has been resolved upstream by our hosting provider - sorry for the annoyance! Can you check https://www.simpla.io again?

**Comment by iamchriswick** [comment]
Worked like a charm 3-4 hours after I first reported the incident. Sorry for the late reply @seaneking :)
