### ISSUE TITLE
[v2] Drop support for bower and don't commit build files

### ISSUE THREAD

**Issue by seaneking** [simplaio/simpla#63]
Use NPMs `prepublish` hook and just support NPM/Yarn and Unpkg. Can't see a use-case for supporting Bower with Simpla itself - anyone that doesn't want to use NPM can use Unpkg?

**Comment by bedeoverend** [comment]
My concern here is if someone is using `bower` for everything, not unsurprising given that's how all our elements are deployed...but having said that, we want to move towards NPM / Yarn anyway, we may as well encourage it, and I doubt anyone will really be running _only_ bower. Plus, we can just add them back in afterwards if people are really needing it

**Comment by seaneking** [comment]
Even if someone is running only Bower, why can't they just link in with Unpkg? Really the only reason to install Simpla locally at all would be to consume it as a module rather than linking in a script tag, which you need NPM for anyway

**Comment by bedeoverend** [comment]
They probably can, but I know devs can get thingy about relying on CDNs - it means it's out of their control. I know I always feel a wee bit funny handing things over to CDNs instead of loading them locally, as I'm no longer in control of the uptime. I know that the CDN will probably be more reliable, but you get the gist.

Aaaanyway, I'm still happy to support only NPM - the fact that Bower itself is recommending using `yarn` or `npm` for new projects is enough to say, mmm k probably don't need to use it _if we don't have to_, which is the case with our elements.

**Comment by seaneking** [comment]
Fixed in https://github.com/simplaio/simpla/commit/6b18c57a504255005b287e2fd86e3e4842ffe106
