### ISSUE TITLE
Create starter kits (Bootstrap, React, etc)

### ISSUE THREAD

**Issue by simplygreatwork** [simplaio/simpla#91]
I wanted to ask a basic question about Simpla but slack.simplajs.org appears to be down. So that's the main issue right now. My original issue is: do any boilerplate projects exist for Simpla? I was a small backer of the Kickerstarter project back in 2015. You guys rock.

**Comment by madeleineostoja** [comment]
First of all, thanks so much for backing us way back when! Glad you're still around.

Simpla's Slack group was a bit of a ghost town, so now that it's a community run project we've decided to close it in favour of using Github issues for everything. If Github gets too hard to manage in future we'll look at making another chat group, maybe on Gitter since it's more open.

We did have a sample template for Simpla v1, but it got lost in the shuffle during the last few updates. We've been wanting to make a collection of Simpla-fied starter kits for popular frameworks (eg: Simpla + create-react-app, Simpla + a Bootstrap template, etc) but haven't gotten around to it.

I'll update this issue to reflect.

**Comment by simplygreatwork** [comment]
Because Simpla is written using web components, maybe a boilerplate project employing web components or Polymer makes sense as a starting point. Other than that, I prefer Vue.js (Vuetify.js) or Riot.js above React or Angular - but that's just a personal preference, I know. If I do manage to contribute a boilerplate project for Simpla, it would use either web components (Polymer) or Vue.js.

**Comment by simplygreatwork** [comment]
In the meantime, the simplajs.org website might serve as a good starter kit for experimentation. I'll take a look.

**Comment by kafkiano** [comment]
@simplygreatwork Hey did you managed to create an boilerplate ? because im right now stuck in the same situation ?

Thx and best regards
Felix
